
markdown = {
  DEFAULT =    { '_DEFLT_FG', 'Normal' },
  LINE_BEGIN = { '_DEFLT_FG', 'Normal' },
  STRONG1 =    { '"#808080"', 'Bold'   },
  STRONG2 =    { '_DEFLT_FG', 'Bold'   },
  EM1 =        { '"#808080"', 'Bold'   },
  EM2 =        { '_DEFLT_FG', 'Bold'   },
  HEADER1 =    { '"#ddb0b0"', 'Bold'   },
  HEADER2 =    { '"#dda0a0"', 'Bold'   },
  HEADER3 =    { '"#dd8080"', 'Bold'   },
  HEADER4 =    { '"#dd6060"', 'Bold'   },
  HEADER5 =    { '"#cc6060"', 'Bold'   },
  HEADER6 =    { '"#bb4040"', 'Bold'   },
  PRECHAR =    { '"#cc00cc"', 'Normal' },
  ULIST_ITEM = { '"#4040e0"', 'Normal' },
  OLIST_ITEM = { '"#4040e0"', 'Normal' },
  BLOCKQUOTE = { '"#00c000"', 'Normal' },
  STRIKEOUT =  { '"#ee0000"', 'Normal' },
  HRULE =      { '"#ffaa00"', 'Normal' },
  LINK =       { '"#0000ee"', 'Bold'   },
  CODE =       { '"#00aaaa"', 'Normal' },
  CODE2 =      { '"#00bbbb"', 'Normal' },
  CODEBK =     { '"#00cccc"', 'Normal' }
}
